In [87]:
import numpy as np

In [88]:
print(np.__version__)
np.show_config()

1.16.2
mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Anaconda3\\Library\\include']


In [89]:
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [90]:
Z = np.zeros((10,10))
print("%d bytes" %(Z.size * Z.itemsize))

800 bytes


In [91]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

In [92]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [93]:
Z = np.arange(10:50)
print(Z)

SyntaxError: invalid syntax (<ipython-input-93-f270c0a63f5f>, line 1)

In [ ]:
Z = np.arange(10,50)
print(Z)

In [ ]:
Z = np.arange(50)
Z = Z[::-1]
print(Z)

In [ ]:
Z = np.arange(9).reshape(3,3)
print(Z)

In [ ]:
Z = np.array([1,2,0,0,4,0])
nz = np.nonzero(Z)
print(nz)

In [ ]:
Z = np.eye(3,3)
print(Z)

In [ ]:
Z = np.random.random(3,3,3)
print(Z)

In [ ]:
Z = np.eye(3,3,3)
print(Z)

In [ ]:
np.info(np.random.random)

In [ ]:
np.info(np.random.randn)

In [ ]:
Z = np.random.random((3,3,3))

In [ ]:
print(Z)

In [ ]:
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

In [ ]:
Z = np.random.random((30,))

In [ ]:
print(Z)

In [ ]:
m = Z.mean()
print(m)

In [ ]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

In [ ]:
Z = np.array([0,1,2,3,4])
print(Z[-1])

In [ ]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

In [ ]:
print(0*np.nan)

In [ ]:
print(np.nan ==np.nan)

In [ ]:
print(np.inf > np.nan)

In [ ]:
print(np.nan - np.nan)

In [ ]:
print(0.3 == 3*0.1)

In [94]:
np.info(np.diag)

 diag(v, k=0)

Extract a diagonal or construct a diagonal array.

See the more detailed documentation for ``numpy.diagonal`` if you use this
function to extract a diagonal and wish to write to the resulting array;
whether it returns a copy or a view depends on what version of numpy you
are using.

Parameters
----------
v : array_like
    If `v` is a 2-D array, return a copy of its `k`-th diagonal.
    If `v` is a 1-D array, return a 2-D array with `v` on the `k`-th
    diagonal.
k : int, optional
    Diagonal in question. The default is 0. Use `k>0` for diagonals
    above the main diagonal, and `k<0` for diagonals below the main
    diagonal.

Returns
-------
out : ndarray
    The extracted diagonal or constructed diagonal array.

See Also
--------
diagonal : Return specified diagonals.
diagflat : Create a 2-D array with the flattened input as a diagonal.
trace : Sum along diagonals.
triu : Upper triangle of an array.
tril : Lower triangle of an array.

Examples
--------
>>> x = np.ar

In [95]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [96]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [97]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


In [98]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))

In [99]:
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [100]:
Z = np.random.random((5,5))
Zmax, Zmin = Z.max(), Z.min()
Z = (Z - Zmin)/(Zmax - Zmin)
print(Z)

[[0.98000364 0.22387415 0.81745556 0.7337836  0.04991751]
 [0.15950549 0.27646084 0.66188868 0.7513051  0.        ]
 [0.27971053 0.1771835  1.         0.3211778  0.98158012]
 [0.1633124  0.2805134  0.68047896 0.82417672 0.05739762]
 [0.92708601 0.52143072 0.6657776  0.48406894 0.8491091 ]]


In [101]:
color = np.dtype([("r", np.ubyte, 1),("g", np.ubyte, 1),("b", np.ubyte, 1),("a", np.ubyte, 1)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [102]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [103]:
Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [104]:
print(sum(range(5),-1))

10


In [105]:
from numpy import *

In [106]:
print(sum(range(5),-1))

10


In [107]:
Z = np.arange(5)

In [108]:
Z ** Z

array([  1,   1,   4,  27, 256], dtype=int32)

In [109]:
2 << Z >> 2 

array([0, 1, 2, 4, 8], dtype=int32)

In [110]:
print(Z)

[0 1 2 3 4]


In [111]:
Z <- Z

array([False, False, False, False, False])

In [112]:
1j*Z

array([0.+0.j, 0.+1.j, 0.+2.j, 0.+3.j, 0.+4.j])

In [113]:
Z = np.arange(5)
Z/1/1

array([0., 1., 2., 3., 4.])

In [114]:
Z

array([0, 1, 2, 3, 4])

In [115]:
Z<Z>Z

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [116]:
print(np.array(0) / np.array(0))

nan


C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [117]:
print(np.array(0) // np.array(0))

0


C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


In [118]:
print(np.array([np.nan]).astype(int).astype(float))

[-2.14748365e+09]


In [119]:
Z = np.random.uniform(-10,+10,10)

In [120]:
Z

array([ 1.62483293,  5.39265658, -4.91970151, -7.10058748, -4.03655558,
       -5.25474773,  6.61924709,  0.80461519,  7.08935312,  8.09340527])

In [121]:
print (np.copysign(np.ceil(np.abs(Z)), Z))

[ 2.  6. -5. -8. -5. -6.  7.  1.  8.  9.]


In [122]:
Z1 = np.random.randint(0,10,10)

In [123]:
Z2 = np.random.randint(0,10,10)

In [124]:
print(np.intersect1d(Z1,Z2))

[2 3 4 5 6]


In [125]:
defaults = np.seterr(all="ignore")

In [126]:
Z = np.ones(1) / 0

In [127]:
_ = np.seterr(**defaults)

In [128]:
with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0

In [129]:
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

In [130]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')

In [131]:
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print ("Yesterday is " + str(yesterday))
print ("Today is " + str(today))
print ("Tomorrow is "+ str(tomorrow))

Yesterday is 2019-06-22
Today is 2019-06-23
Tomorrow is 2019-06-24


In [133]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [134]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)

array([3., 3., 3.])

In [135]:
np.divide(A,2,out=A)

array([0.5, 0.5, 0.5])

In [136]:
np.negative(A,out=A)

array([-0.5, -0.5, -0.5])

In [137]:
np.negative(A,out=A)

array([0.5, 0.5, 0.5])

In [138]:
np.negative(A,out=A)

array([-0.5, -0.5, -0.5])

In [139]:
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

In [140]:
Z = np.random.uniform(0,10,10)
print (Z - Z%1)

[1. 0. 0. 0. 1. 8. 6. 3. 7. 1.]


In [141]:
print (np.floor(Z))

[1. 0. 0. 0. 1. 8. 6. 3. 7. 1.]


In [142]:
print (np.ceil(Z)-1)

[1. 0. 0. 0. 1. 8. 6. 3. 7. 1.]


In [143]:
print (Z.astype(int))

[1 0 0 0 1 8 6 3 7 1]


In [144]:
print (np.trunc(Z))

[1. 0. 0. 0. 1. 8. 6. 3. 7. 1.]


In [145]:
Z = np.zeros((5,5))
Z += np.arange(5)
Z

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [146]:
def generate():
    for x in range(10):
        yield x

In [147]:
Z = np.fromiter(generate(),dtype=float,count=-1)

In [149]:
Z

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [150]:
Z = np.linspace(0,1,11,endpoint=False)[1:]

In [151]:
Z

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

In [152]:
Z = np.random.random(10)
Z.sort()
print (Z)

[0.07045213 0.07460442 0.13811523 0.21344453 0.31442312 0.41942886
 0.49539113 0.75776346 0.87694888 0.98388346]


In [153]:
Z = np.arange(10)
np.add.reduce(Z)

45

In [154]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

equal = np.allclose(A,B)
print(equal)

False


In [155]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

In [156]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print (R)
print (T)

[1.20674128 0.69439324 1.21515865 0.52220858 0.30792249 0.93535703
 1.13465959 0.90438967 1.0058266  1.08994468]
[0.69968459 0.96886042 0.84633866 0.77159862 0.71764998 0.29932455
 0.8321136  1.06872521 1.22963094 0.88632262]


In [158]:
Z = np.random.random(10)
Z[Z.argmax()] = 1
print (Z)

[0.09940457 0.47115244 0.8707323  0.16749998 0.51269991 0.46452006
 0.18591752 0.46684502 0.21832594 1.        ]


In [159]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                              np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [160]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))


3638.1636371179666


In [161]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)

for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [162]:
np.set_printoptions(threshold=np.nan)
Z = np.zeros((16,16))
print (Z)

ValueError: threshold must be numeric and non-NAN, try sys.maxsize for untruncated representation

In [163]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print (Z[index])

38


In [164]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print (Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


In [165]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print (D)

[[0.         0.65554849 0.78880367 0.51822867 0.89941149 0.35787586
  0.82524933 0.57258619 0.29495379 0.95801195]
 [0.65554849 0.         0.97157987 0.9327807  0.53441134 0.35537446
  0.39325564 0.40059021 0.85713334 0.54059449]
 [0.78880367 0.97157987 0.         0.35450779 0.69313585 0.6896363
  0.75963267 0.5749428  0.59523252 0.76956685]
 [0.51822867 0.9327807  0.35450779 0.         0.85842091 0.58478258
  0.86794283 0.6064319  0.2601334  0.93608212]
 [0.89941149 0.53441134 0.69313585 0.85842091 0.         0.55646257
  0.14335432 0.32718843 0.9378274  0.07859621]
 [0.35787586 0.35537446 0.6896363  0.58478258 0.55646257 0.
  0.46957604 0.24207414 0.50598202 0.60828712]
 [0.82524933 0.39325564 0.75963267 0.86794283 0.14335432 0.46957604
  0.         0.27661931 0.90677191 0.1532356 ]
 [0.57258619 0.40059021 0.5749428  0.6064319  0.32718843 0.24207414
  0.27661931 0.         0.63020075 0.3897189 ]
 [0.29495379 0.85713334 0.59523252 0.2601334  0.9378274  0.50598202
  0.90677191 0.630200

In [166]:
Z = np.arange(10, dtype=np.int32)
Z = Z.astype(np.float32, copy=False)
print (Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [167]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print (index, value)
for index in np.ndindex(Z.shape):
    print (index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [168]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print (G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

In [169]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print (Z)

[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]]


In [170]:
X = np.random.rand(5, 10)

Y = X - X.mean(axis=1, keepdims=True)
print(Y)

[[ 0.39702016 -0.15196657 -0.13624082  0.35062924 -0.31922008 -0.04120625
   0.13807351  0.20893383 -0.38898437 -0.05703863]
 [ 0.02926192  0.02730608 -0.32908921 -0.34267234  0.18101388  0.28465375
   0.22712126 -0.25759094  0.25012006 -0.07012445]
 [ 0.33691606  0.25651491 -0.09185518  0.052287   -0.38007355  0.09043819
  -0.04878512 -0.47136492 -0.21296214  0.46888474]
 [ 0.05980456  0.22989972 -0.1953007   0.39347603  0.2836751  -0.12770924
   0.25278485 -0.20315905 -0.51999147 -0.17347981]
 [ 0.03939365 -0.41527195 -0.1517282   0.36261886 -0.24731306 -0.02857598
  -0.37739955  0.47014056  0.39147459 -0.04333893]]


In [171]:
Z = np.random.randint(0,10,(3,3))
print (Z)
print (Z[Z[:,1].argsort()])

[[3 5 0]
 [6 1 4]
 [9 2 6]]
[[6 1 4]
 [9 2 6]
 [3 5 0]]


In [172]:
Z = np.random.randint(0,3,(3,10))
print ((~Z.any(axis=0)).any())

False


In [174]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print (m)

0.5226681824669419


In [175]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: 
    z[...] = x + y
print (it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [176]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


In [177]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[7. 2. 2. 1. 3. 4. 4. 3. 1. 3.]


In [178]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print (F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


In [179]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)


F = I[...,0]*(256*256) + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print (n)


8


In [180]:
A = np.random.randint(0,10,(3,4,3,4))

sum = A.sum(axis=(-2,-1))
print (sum)

[[63 44 58 61]
 [22 52 75 57]
 [60 64 50 73]]


In [181]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print (D_means)

[0.56887075 0.57395639 0.29788863 0.43206153 0.39006307 0.1757226
 0.44032704 0.40937568 0.53500103 0.55750917]


In [182]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

np.diag(np.dot(A, B))

array([0.6150829 , 1.27898353, 0.60169605, 0.97381181, 1.03948418])

In [183]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print (Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


In [184]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print (A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


In [185]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print (A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [186]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print (G)

[( 4, 41) ( 4, 72) ( 8, 41) ( 8, 92) (12, 78) (12, 88) (14, 22) (14, 51)
 (22, 51) (28, 31) (28, 53) (28, 80) (28, 96) (31, 96) (34, 85) (34, 88)
 (35, 39) (35, 78) (35, 85) (35, 86) (39, 85) (41, 72) (41, 92) (52, 85)
 (52, 88) (53, 80) (78, 86) (78, 88) (85, 88)]


In [187]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print (A)

[1 1 2 3 4 4 6]


In [188]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)

print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


In [189]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)

print (Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


In [190]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

array([1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0])

In [191]:
Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([-0.07709924, -0.1987325 , -0.49003879,  0.38775171, -0.38132961,
       -0.38821306, -0.8587818 ,  0.71665835, -0.33570033, -0.36122366,
        0.90600846,  0.91805768, -0.31235941,  0.0560691 , -0.17662052,
        0.5149764 , -0.61405118,  0.36223703,  0.97457035,  0.28413032,
        0.43188918,  0.23413876,  0.31312599, -0.86317429,  0.18077465,
       -0.74547771,  0.59674432, -0.70529055, -0.32346505,  0.25116004,
        0.0703018 , -0.54444679,  0.38141509,  0.36402777, -0.69768639,
        0.38719726,  0.97814815,  0.83081703, -0.63009679, -0.69314772,
        0.06088204,  0.69219076, -0.41931869,  0.10412496,  0.05603061,
       -0.93968133, -0.69037091,  0.12531318,  0.14678852, -0.17402626,
        0.58849483,  0.42087146,  0.76460057,  0.76717512,  0.03155235,
       -0.62429202, -0.34518434, -0.74344466,  0.85045373, -0.75625302,
       -0.30874338,  0.5974038 ,  0.24644055,  0.57699146,  0.46557088,
       -0.63744567,  0.19459244, -0.23111529,  0.47368575, -0.24

In [192]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))


In [193]:
P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))

print (distance(P0, P1, p))

[ 4.02215104  1.13771694  9.96531821  4.22149507  3.06356181  0.056785
 14.598834    1.27320196 12.27684045  4.79059901]


In [194]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print (np.array([distance(P0,P1,p_i) for p_i in p]))

[[11.47921915  3.80060604 11.87984401  6.12965388  2.5488707   8.78416593
   4.37183759 10.14892694 11.26979044 11.52265181]
 [ 0.37111013 10.38873841  2.5877012   5.0536283   6.20782856  2.4572485
   6.8744679   1.21450513  3.68310498  1.47370757]
 [ 7.11263999  6.41835697  8.25596132  1.7467637   0.91272592  4.36846519
   0.04561656  6.66714409  8.26301084  7.56087682]
 [ 5.29728555  8.04705977  7.30670627  0.18045122  2.72579401  2.59607845
   1.81546172  5.80556915  6.54022112  5.69060247]
 [ 6.83799599  3.21968819  4.55935434  0.12107658  1.19690685  3.69621373
   0.73833326  2.80145306 11.01619386  8.70090517]
 [10.08816016  1.87362983  7.87798535  3.42640265  3.35661399  7.0536027
   2.62400661  6.04620082 12.72722544 11.40094026]
 [ 5.81616533  4.32360731  4.70004747  5.00765976  6.03057813  1.70620145
   2.77811562  6.8563896  17.44750617 11.1425735 ]
 [ 9.11552785  3.81011947  0.60763042  0.51654007  6.92210439  5.33492711
   0.86701325  1.52420835 17.53984319 13.10698157]
 [

In [195]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print (Z)
print (R)

[[2 7 7 9 6 2 9 5 6 5]
 [7 4 8 6 4 2 1 5 1 4]
 [1 6 7 0 7 4 9 0 8 2]
 [6 4 8 8 3 2 3 0 3 2]
 [3 6 6 4 4 3 4 6 0 4]
 [0 3 8 7 8 5 3 7 4 1]
 [0 4 0 0 0 1 9 7 3 3]
 [8 3 5 6 4 0 7 2 5 5]
 [5 5 9 3 8 8 0 2 1 1]
 [3 8 7 1 0 4 1 9 8 0]]
[[0 0 0 0 0]
 [0 2 7 7 9]
 [0 7 4 8 6]
 [0 1 6 7 0]
 [0 6 4 8 8]]


C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


In [196]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print (R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


In [197]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print (rank)

10


In [198]:
Z = np.random.randint(0,10,50)
print (np.bincount(Z).argmax())

2


In [199]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print (C)

[[[[2 0 0]
   [4 3 1]
   [0 2 4]]

  [[0 0 2]
   [3 1 4]
   [2 4 2]]

  [[0 2 0]
   [1 4 3]
   [4 2 2]]

  [[2 0 0]
   [4 3 3]
   [2 2 0]]

  [[0 0 4]
   [3 3 4]
   [2 0 0]]

  [[0 4 3]
   [3 4 1]
   [0 0 0]]

  [[4 3 1]
   [4 1 4]
   [0 0 2]]

  [[3 1 3]
   [1 4 1]
   [0 2 4]]]


 [[[4 3 1]
   [0 2 4]
   [4 0 2]]

  [[3 1 4]
   [2 4 2]
   [0 2 4]]

  [[1 4 3]
   [4 2 2]
   [2 4 3]]

  [[4 3 3]
   [2 2 0]
   [4 3 0]]

  [[3 3 4]
   [2 0 0]
   [3 0 4]]

  [[3 4 1]
   [0 0 0]
   [0 4 1]]

  [[4 1 4]
   [0 0 2]
   [4 1 4]]

  [[1 4 1]
   [0 2 4]
   [1 4 2]]]


 [[[0 2 4]
   [4 0 2]
   [4 2 2]]

  [[2 4 2]
   [0 2 4]
   [2 2 1]]

  [[4 2 2]
   [2 4 3]
   [2 1 0]]

  [[2 2 0]
   [4 3 0]
   [1 0 0]]

  [[2 0 0]
   [3 0 4]
   [0 0 4]]

  [[0 0 0]
   [0 4 1]
   [0 4 4]]

  [[0 0 2]
   [4 1 4]
   [4 4 1]]

  [[0 2 4]
   [1 4 2]
   [4 1 4]]]


 [[[4 0 2]
   [4 2 2]
   [2 0 1]]

  [[0 2 4]
   [2 2 1]
   [0 1 3]]

  [[2 4 3]
   [2 1 0]
   [1 3 1]]

  [[4 3 0]
   [1 0 0]
   [3 1 1]]

  [[3 0 4]
   

In [200]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print (S)

[[ 9  5  5 16  2]
 [ 5  5  5 16 14]
 [ 5  5  3 42  7]
 [16 16 42  5 10]
 [ 2 14  7 10  6]]


In [201]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print (S)

M is (p,n,n)
V is (p,n,1)
#

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


False

In [202]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print (S)


[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


In [203]:
def iterate(Z):

    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print (Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [204]:
print (Z[np.argpartition(-Z,n)[:n]])

[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 1 1 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 1 1 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 ...

 [[0 0 0 ... 1 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]


In [205]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))


[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


In [206]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T, 
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print (R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


In [207]:
x = np.random.rand()
np.power(x,3)

0.20711512866186826

In [208]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print (rows)

[0 1 2 4]


In [209]:
Z = np.random.randint(0,5,(10,3))
print (Z)


E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print (U)

[[0 2 0]
 [4 2 1]
 [3 3 2]
 [3 4 3]
 [2 3 0]
 [1 3 1]
 [1 3 2]
 [3 4 2]
 [3 1 4]
 [3 4 2]]
[[0 2 0]
 [4 2 1]
 [3 3 2]
 [3 4 3]
 [2 3 0]
 [1 3 1]
 [1 3 2]
 [3 4 2]
 [3 1 4]
 [3 4 2]]


In [210]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


In [211]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print (uZ)

[[0 0 0]
 [0 0 1]
 [0 1 1]
 [1 0 0]
 [1 1 0]
 [1 1 1]]


In [212]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)
print ('sum')
print (np.einsum('i->', A))# np.sum(A)

sum
4.095612444741854


In [213]:
print ('A * B')
print (np.einsum('i,i->i', A, B)) # A * B

A * B
[0.18996172 0.09689542 0.07973404 0.46922386 0.46081158 0.00945252
 0.00281028 0.05952063 0.4081683  0.08115723]


In [214]:
print ('inner')
print (np.einsum('i,i', A, B))    # np.inner(A, B)

inner
1.8577355766946613


In [215]:
print ('outer')
print (np.einsum('i,j->ij', A, B))    # np.outer(A, B)

outer
[[0.18996172 0.13447847 0.14933897 0.53065582 0.46033444 0.03499533
  0.00727947 0.18463504 0.56109823 0.24733102]
 [0.13687262 0.09689542 0.10760282 0.38235205 0.33168357 0.0252151
  0.00524506 0.1330346  0.40428664 0.17820877]
 [0.10142307 0.07179983 0.07973404 0.28332414 0.24577863 0.01868447
  0.0038866  0.09857908 0.29957775 0.13205329]
 [0.16797059 0.11891042 0.13205058 0.46922386 0.40704331 0.03094406
  0.00643675 0.16326056 0.49614207 0.21869847]
 [0.19015862 0.13461786 0.14949376 0.53120585 0.46081158 0.03503161
  0.00728701 0.18482641 0.56167981 0.24758738]
 [0.05131016 0.0363237  0.04033764 0.14333433 0.12433997 0.00945252
  0.00196624 0.04987138 0.15155707 0.06680606]
 [0.07333581 0.05191618 0.05765316 0.2048627  0.17771473 0.01351015
  0.00281028 0.07127941 0.21661517 0.09548355]
 [0.06123779 0.0433517  0.04814227 0.17106703 0.14839759 0.01128141
  0.00234668 0.05952063 0.18088072 0.07973187]
 [0.13818677 0.09782574 0.10863594 0.38602311 0.33486815 0.02545719
  0.005

In [216]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

In [217]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print (X[M])

[[2. 0. 1. 1.]]


In [218]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print (confint)

[-0.24415297  0.1860977 ]
